BoostInstallPath=/home/brichards/boost_1_60_0/install



all:
	g++ main.cpp ../src/Store2.cpp -o main -I ./ -I ../src/ -L $(BoostInstallPath)/lib/ -lboost_serialization -I $(BoostInstallPath)/include/

